/**
 * Syntegrity geometries — the precomputed strut tables per shape.
 *
 * WHY THESE ARE HARD-CODED, NOT COMPUTED AT RUNTIME
 * The member structure of a polyhedron (which vertices an edge touches) is
 * trivial, but the *critic* structure (which 2 non-incident teams each strut
 * critiques such that every team receives exactly `teamSize` critics) is a
 * balanced combinatorial design. Beer/Truss solved these by hand per solid.
 * We treat them as fixed, validated lookup tables. The only runtime computation
 * is matching PEOPLE to struts (the role-assignment scripts).
 *
 * STATUS: the tetrahedron is fully encoded and hand-verifiable, so the scripts
 * and scheduler have a real, testable shape today. The larger solids are
 * registered with their metadata but their strut/face tables are pending
 * (TODO: encode + unit-test member/critic balance for each). Keeping each shape
 * behind `getShape()` means scripts never hard-depend on a half-filled table.
 */

import type { ShapeName, StrutSlot, SyntegrityShape } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// Shape metadata (counts only) — always known, even before the table is encoded.
// ─────────────────────────────────────────────────────────────────────────────

export interface ShapeMeta {
  name: ShapeName;
  participantCount: number; // edges
  topicCount: number; // vertices
  teamSize: number; // vertex degree
  faceCount: number;
  /** True only for all-triangle (deltahedron) shapes => clean groups-of-3 Face Planning. */
  uniformTriangularFaces: boolean;
}

export const SHAPE_META: Record<ShapeName, ShapeMeta> = {
  tetrahedron: { name: 'tetrahedron', participantCount: 6, topicCount: 4, teamSize: 3, faceCount: 4, uniformTriangularFaces: true },
  octahedron: { name: 'octahedron', participantCount: 12, topicCount: 6, teamSize: 4, faceCount: 8, uniformTriangularFaces: true },
  cube: { name: 'cube', participantCount: 12, topicCount: 8, teamSize: 3, faceCount: 6, uniformTriangularFaces: false },
  cuboctahedron: { name: 'cuboctahedron', participantCount: 24, topicCount: 12, teamSize: 4, faceCount: 14, uniformTriangularFaces: false },
  icosahedron: { name: 'icosahedron', participantCount: 30, topicCount: 12, teamSize: 5, faceCount: 20, uniformTriangularFaces: true },
  icosidodecahedron: { name: 'icosidodecahedron', participantCount: 60, topicCount: 30, teamSize: 4, faceCount: 32, uniformTriangularFaces: false },
};

// ─────────────────────────────────────────────────────────────────────────────
// Tetrahedron — fully encoded reference instance.
//
// Vertices 0,1,2,3. Edges as (a,b). A strut critiques the OPPOSITE edge's two
// vertices (the only 2 vertices it doesn't touch). Hand-checked: every vertex is
// touched by 3 struts (3 members) and named as critic-target by 3 struts
// (3 critics) — matching teamSize 3.
// ─────────────────────────────────────────────────────────────────────────────

const TETRAHEDRON_STRUTS: StrutSlot[] = [
  { id: 0, memberOf: [0, 1], criticOf: [2, 3] },
  { id: 1, memberOf: [0, 2], criticOf: [1, 3] },
  { id: 2, memberOf: [0, 3], criticOf: [1, 2] },
  { id: 3, memberOf: [1, 2], criticOf: [0, 3] },
  { id: 4, memberOf: [1, 3], criticOf: [0, 2] },
  { id: 5, memberOf: [2, 3], criticOf: [0, 1] },
];

// Triangular faces as strut-id triples (for later Face Planning).
const TETRAHEDRON_FACES: number[][] = [
  [0, 1, 3], // vertices {0,1,2}
  [0, 2, 4], // vertices {0,1,3}
  [1, 2, 5], // vertices {0,2,3}
  [3, 4, 5], // vertices {1,2,3}
];

const TETRAHEDRON: SyntegrityShape = {
  name: 'tetrahedron',
  participantCount: 6,
  topicCount: 4,
  teamSize: 3,
  faceCount: 4,
  struts: TETRAHEDRON_STRUTS,
  faces: TETRAHEDRON_FACES,
};

// ─────────────────────────────────────────────────────────────────────────────
// Octahedron (12 people / 6 topics / teams of 4).
// Generated by _generate-shapes.ts from vertex coordinates and validated:
// critics of a strut = the two apex vertices of the two triangles on that edge.
// Vertices: 0=+x 1=-x 2=+y 3=-y 4=+z 5=-z (antipodal pairs 0/1, 2/3, 4/5).
// ─────────────────────────────────────────────────────────────────────────────

const OCTAHEDRON_STRUTS: StrutSlot[] = [
  { id: 0, memberOf: [0, 2], criticOf: [4, 5] },
  { id: 1, memberOf: [0, 3], criticOf: [4, 5] },
  { id: 2, memberOf: [0, 4], criticOf: [2, 3] },
  { id: 3, memberOf: [0, 5], criticOf: [2, 3] },
  { id: 4, memberOf: [1, 2], criticOf: [4, 5] },
  { id: 5, memberOf: [1, 3], criticOf: [4, 5] },
  { id: 6, memberOf: [1, 4], criticOf: [2, 3] },
  { id: 7, memberOf: [1, 5], criticOf: [2, 3] },
  { id: 8, memberOf: [2, 4], criticOf: [0, 1] },
  { id: 9, memberOf: [2, 5], criticOf: [0, 1] },
  { id: 10, memberOf: [3, 4], criticOf: [0, 1] },
  { id: 11, memberOf: [3, 5], criticOf: [0, 1] },
];
const OCTAHEDRON_FACES: number[][] = [
  [0, 8, 2], [0, 9, 3], [1, 10, 2], [1, 11, 3],
  [4, 8, 6], [4, 9, 7], [5, 10, 6], [5, 11, 7],
];

const OCTAHEDRON: SyntegrityShape = {
  name: 'octahedron',
  participantCount: 12,
  topicCount: 6,
  teamSize: 4,
  faceCount: 8,
  struts: OCTAHEDRON_STRUTS,
  faces: OCTAHEDRON_FACES,
};

// ─────────────────────────────────────────────────────────────────────────────
// Icosahedron (30 people / 12 topics / teams of 5) — Beer's canonical form.
// Generated by _generate-shapes.ts from golden-ratio vertex coordinates and
// validated (same critic rule). Vertex indices are an internal labelling; topics
// bind to them by array order at finalization.
// ─────────────────────────────────────────────────────────────────────────────

const ICOSAHEDRON_STRUTS: StrutSlot[] = [
  { id: 0, memberOf: [0, 2], criticOf: [8, 10] },
  { id: 1, memberOf: [0, 4], criticOf: [6, 8] },
  { id: 2, memberOf: [0, 6], criticOf: [4, 10] },
  { id: 3, memberOf: [0, 8], criticOf: [2, 4] },
  { id: 4, memberOf: [0, 10], criticOf: [2, 6] },
  { id: 5, memberOf: [1, 3], criticOf: [9, 11] },
  { id: 6, memberOf: [1, 4], criticOf: [6, 9] },
  { id: 7, memberOf: [1, 6], criticOf: [4, 11] },
  { id: 8, memberOf: [1, 9], criticOf: [3, 4] },
  { id: 9, memberOf: [1, 11], criticOf: [3, 6] },
  { id: 10, memberOf: [2, 5], criticOf: [7, 8] },
  { id: 11, memberOf: [2, 7], criticOf: [5, 10] },
  { id: 12, memberOf: [2, 8], criticOf: [0, 5] },
  { id: 13, memberOf: [2, 10], criticOf: [0, 7] },
  { id: 14, memberOf: [3, 5], criticOf: [7, 9] },
  { id: 15, memberOf: [3, 7], criticOf: [5, 11] },
  { id: 16, memberOf: [3, 9], criticOf: [1, 5] },
  { id: 17, memberOf: [3, 11], criticOf: [1, 7] },
  { id: 18, memberOf: [4, 6], criticOf: [0, 1] },
  { id: 19, memberOf: [4, 8], criticOf: [0, 9] },
  { id: 20, memberOf: [4, 9], criticOf: [1, 8] },
  { id: 21, memberOf: [5, 7], criticOf: [2, 3] },
  { id: 22, memberOf: [5, 8], criticOf: [2, 9] },
  { id: 23, memberOf: [5, 9], criticOf: [3, 8] },
  { id: 24, memberOf: [6, 10], criticOf: [0, 11] },
  { id: 25, memberOf: [6, 11], criticOf: [1, 10] },
  { id: 26, memberOf: [7, 10], criticOf: [2, 11] },
  { id: 27, memberOf: [7, 11], criticOf: [3, 10] },
  { id: 28, memberOf: [8, 9], criticOf: [4, 5] },
  { id: 29, memberOf: [10, 11], criticOf: [6, 7] },
];
const ICOSAHEDRON_FACES: number[][] = [
  [0, 12, 3], [0, 13, 4], [1, 18, 2], [1, 19, 3], [2, 24, 4],
  [5, 16, 8], [5, 17, 9], [6, 18, 7], [6, 20, 8], [7, 25, 9],
  [10, 21, 11], [10, 22, 12], [11, 26, 13], [14, 21, 15], [14, 23, 16],
  [15, 27, 17], [19, 28, 20], [22, 28, 23], [24, 29, 25], [26, 29, 27],
];

const ICOSAHEDRON: SyntegrityShape = {
  name: 'icosahedron',
  participantCount: 30,
  topicCount: 12,
  teamSize: 5,
  faceCount: 20,
  struts: ICOSAHEDRON_STRUTS,
  faces: ICOSAHEDRON_FACES,
};

/** Shapes whose strut/face tables are fully encoded and validated today. */
const ENCODED_SHAPES: Partial<Record<ShapeName, SyntegrityShape>> = {
  tetrahedron: TETRAHEDRON,
  octahedron: OCTAHEDRON,
  icosahedron: ICOSAHEDRON,
  // TODO (non-deltahedra, need a different critic rule): cube, cuboctahedron, icosidodecahedron.
};

// ─────────────────────────────────────────────────────────────────────────────
// Public helpers
// ─────────────────────────────────────────────────────────────────────────────

export class ShapeNotEncodedError extends Error {
  readonly shape: ShapeName;
  constructor(shape: ShapeName) {
    super(`Strut table for "${shape}" is not encoded yet (only metadata is known).`);
    this.name = 'ShapeNotEncodedError';
    this.shape = shape;
  }
}

/** Get a fully-encoded shape, or throw if its table is still pending. */
export function getShape(name: ShapeName): SyntegrityShape {
  const shape = ENCODED_SHAPES[name];
  if (!shape) throw new ShapeNotEncodedError(name);
  return shape;
}

export function isShapeEncoded(name: ShapeName): boolean {
  return ENCODED_SHAPES[name] !== undefined;
}

/**
 * Pick the recommended shape for a headcount, following the spec's rule
 * "fit the group to the shape, not the shape to the group". Returns the shape
 * meta plus how many participants to pad/trim to land exactly on it. At 12 the
 * caller is told octahedron is the default but cube is an alternative.
 */
export interface ShapeRecommendation {
  recommended: ShapeMeta;
  /** + => recruit this many more; - => trim this many; 0 => exact. */
  delta: number;
  alternative?: ShapeMeta;
  note?: string;
}

export function recommendShape(headcount: number): ShapeRecommendation {
  const order: ShapeName[] = ['tetrahedron', 'octahedron', 'cuboctahedron', 'icosahedron', 'icosidodecahedron'];

  if (headcount <= 6) {
    return { recommended: SHAPE_META.tetrahedron, delta: 6 - headcount };
  }
  if (headcount === 12) {
    return {
      recommended: SHAPE_META.octahedron,
      delta: 0,
      alternative: SHAPE_META.cube,
      note: 'Octahedron = 6 topics / teams of 4. Cube = 8 topics / teams of 3.',
    };
  }

  // Snap to the nearest exact participant count among the primary forms.
  let best = SHAPE_META[order[0]];
  let bestDist = Math.abs(headcount - best.participantCount);
  for (const name of order) {
    const m = SHAPE_META[name];
    const d = Math.abs(headcount - m.participantCount);
    if (d < bestDist) {
      best = m;
      bestDist = d;
    }
  }
  return { recommended: best, delta: best.participantCount - headcount };
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation — run on any candidate table to confirm it satisfies the invariants.
// Used by unit tests when new shape tables are encoded.
// ─────────────────────────────────────────────────────────────────────────────

export interface ShapeValidation {
  ok: boolean;
  errors: string[];
}

export function validateShape(shape: SyntegrityShape): ShapeValidation {
  const errors: string[] = [];
  const { struts, participantCount, topicCount, teamSize } = shape;

  if (struts.length !== participantCount) {
    errors.push(`struts.length (${struts.length}) !== participantCount (${participantCount})`);
  }

  const memberCount = new Array(topicCount).fill(0);
  const criticCount = new Array(topicCount).fill(0);

  for (const s of struts) {
    const member = new Set(s.memberOf);
    const critic = new Set(s.criticOf);
    if (member.size !== 2) errors.push(`strut ${s.id}: memberOf must be 2 distinct vertices`);
    if (critic.size !== 2) errors.push(`strut ${s.id}: criticOf must be 2 distinct vertices`);
    for (const v of s.criticOf) {
      if (member.has(v)) errors.push(`strut ${s.id}: critiques a team it is a member of (vertex ${v})`);
    }
    for (const v of s.memberOf) memberCount[v]++;
    for (const v of s.criticOf) criticCount[v]++;
  }

  for (let v = 0; v < topicCount; v++) {
    if (memberCount[v] !== teamSize) errors.push(`vertex ${v}: ${memberCount[v]} members, expected ${teamSize}`);
    if (criticCount[v] !== teamSize) errors.push(`vertex ${v}: ${criticCount[v]} critics, expected ${teamSize}`);
  }

  return { ok: errors.length === 0, errors };
}
